version: '2'
services:
  redis:
    image: redis:latest
    container_name: cache
    ports:
      - 6379:6379
    expose:
      - "6379"
  app:
    image: node:11
    container_name: wthc
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: yarn run start
    ports:
      - 3000:3000
      - 35729:35729
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
    links:
      - redis
